spring.application.name=agriculture-management

# Database Configuration
spring.datasource.url=jdbc:postgresql://dpg-d6sov64r85hc73evk270-a.oregon-postgres.render.com:5432/agridb_xamn
spring.datasource.username=mydb_user_Yashaswini
spring.datasource.password=0XP6n4yu0K33Cy7Yv7N9LYzZZQ1hI348
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=VGhpc0lzQVNlY3VyZUtleUZvckpXVEF1dGhUaGF0SXNMb25nRW5vdWdoMTIz
jwt.expiration=86400000

# Server
server.port=8080

# Logging
logging.level.com.agriculture=DEBUG
anthropic.api.key=your-api-key-here

#postgresql://agridb_xamn_user:0XP6n4yu0K33Cy7Yv7N9LYzZZQ1hI348@dpg-d6sov64r85hc73evk270-a.oregon-postgres.render.com/agridb_xamn